### ISSUE TITLE
Issues while running extract.R

### ISSUE THREAD

**Issue by iamnagesh** [perdoperdo/dsb#1]
I think line 303 in extract.R
`SliceOrder < slice$SliceOrder, # closer to middle`

should be
`SliceOrder <- slice$SliceOrder, # closer to middle`

or it is throwing the following error,
`Error in eval(expr, envir, enclos) : object 'SliceOrder' not found`

**Comment by operdeck** [comment]
No, it should be SliceOrder < slice$SliceOrder. It's a comparison part of the filter expression. Have you loaded **dplyr**? Otherwise it might take a different 'filter' and perhaps don't understand the SliceOrder which is a reference by name into the data passed into the filter.

**Comment by iamnagesh** [comment]
I'm executing the files in the following order,
1. utils.R
2. playlist.R
3. extract.R

is this order correct? I have also updated and loaded the dplyr package.

![error_sliceorder](https://cloud.githubusercontent.com/assets/16324165/14170942/e2636992-f74d-11e5-8526-321c50f7ad20.png)

**Comment by iamnagesh** [comment]
To which data frame do these underlined **SliceOrder** belong to?
![error_sliceorder](https://cloud.githubusercontent.com/assets/16324165/14172296/f93f9396-f754-11e5-860f-ad42815d6b6d.png)

**Comment by iamnagesh** [comment]
```
Processing 1 / 135 : train 1 slice 13 (9/16 order:1) Re-segmenting
pLV summary for this slice (best pLV for every image):
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   -Inf    -Inf    -Inf    -Inf    -Inf    -Inf 
... 265 segments in 30 images
[1] "Existing:"
 [1] "Dataset"        "Id"             "ImgType"        "Slice"         
 [5] "FileName"       "Offset"         "Time"           "SliceCount"    
 [9] "SliceIndex"     "SliceOrder"     "PixelSpacing.x" "PixelSpacing.y"
[13] "SliceLocation"  "SliceThickness" "PatientsSex"    "PatientsAge"   
[1] "New:"
 [1] "Id"             "Slice"          "Time"           "segIndex"      
 [5] "UUID"           "m.cx"           "m.cy"           "m.majoraxis"   
 [9] "m.eccentricity" "m.theta"        "s.area"         "s.perimeter"   
[13] "s.radius.mean"  "s.radius.sd"    "s.radius.min"   "s.radius.max"  
[17] "ROI.x"          "ROI.y"          "ROI.r"         
[1] "- Dataset, - ImgType, - FileName, - Offset, - SliceCount, - SliceIndex, - SliceOrder, - PixelSpacing.x, - PixelSpacing.y, - SliceLocation, - SliceThickness, - PatientsSex, - PatientsAge, + segIndex, + UUID, + m.cx, + m.cy, + m.majoraxis, + m.eccentricity, + m.theta, + s.area, + s.perimeter, + s.radius.mean, + s.radius.sd, + s.radius.min, + s.radius.max, + ROI.x, + ROI.y, + ROI.r"
Error: Datasets do not match up. Please consider removing segment files.
In addition: There were 30 warnings (use warnings() to see them)

```

I get the above error when the above(in image) underlined `Sliceorder` is replaced with `allSegments$SliceOrder` or `imageList$SliceOrder`

```
  previousImages <- filter(left_join(filter(allSegments, Id==slice$Id, Slice!=slice$Slice), 
                                  #Id, Slice, starts_with("ROI.")),
                           imageList, by=c("Id", "Slice", "Time")), 
                           allSegments$SliceOrder < slice$SliceOrder, # closer to middle
                 ((allSegments$SliceOrder == 1) | (allSegments$SliceOrder%%2 == slice$SliceOrder%%2))) # same side of middle; maybe only last few
```

or

```
 previousImages <- filter(left_join(filter(allSegments, Id==slice$Id, Slice!=slice$Slice), 
                                  #Id, Slice, starts_with("ROI.")),
                           imageList, by=c("Id", "Slice", "Time")), 
                           imageList$SliceOrder < slice$SliceOrder, # closer to middle
                 ((imageList$SliceOrder == 1) | (imageList$SliceOrder%%2 == slice$SliceOrder%%2))) # same side of middle; maybe only last few
```

**Comment by operdeck** [comment]
Hmm, I need to check my notes, which are on my other computer tomorrow. You should not run Utils.R separately, it's just a bunch of subroutines. If I remember correctly, you need to
1. Extract all the image files into a "data" subfolder. The "data" subfolder is hardcoded in playlist.R. Below data there can be "train", "test" or "validate" subfolders - depending on which dataset you're using. Remove "imagelist.csv" if that already exists (perhaps I made it part of the repo)
2. Run "playlist.R" which indexes all the images and recreates imagelist.csv. Takes a while as it also reads the meta info.
3. Now run "extract.R"

Once that's done, you should be able to run "classify.R" to manually label a bunch of images, then finally "predict.R".

I believe the README.md explains this too. I'll try run it again from scratch tomorrow to see if I get the same as you,

**Comment by shuklaaks** [comment]
Hi, Me too was getting the same error that "iamnagesh" mentioning even after exploring all steps that you had explain.Requesting you to help me on running this code fully as it was first time I had seen full R code for image processing.

**Comment by operdeck** [comment]
Hi - ok, I'll need to re-download the data because I wiped it from my computer to save some space. Will get back to you...

**Comment by shuklaaks** [comment]
Hi....any luck ..!!

**Comment by shuklaaks** [comment]
Hi ..waiting your update on the same..

**Comment by operdeck** [comment]
Instead of waiting, you better just fix it. Can't be that hard - it's just a bit of simple R code.
